# Generated by Django 2.0.5 on 2018-07-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('street_number', models.CharField(max_length=64)),
                ('flat_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('email_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Grupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osoba', to='userstories.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('phone_type', models.CharField(max_length=32)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefon', to='userstories.Osoba')),
            ],
        ),
        migrations.AddField(
            model_name='grupy',
            name='osoby',
            field=models.ManyToManyField(related_name='grupy', to='userstories.Osoba'),
        ),
        migrations.AddField(
            model_name='email',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='userstories.Osoba'),
        ),
    ]
