# Generated by Django 2.0.5 on 2018-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupy',
            name='group_name',
            field=models.CharField(default='podstawowa', max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(1, 'email prywatny'), (2, 'email służbowy')]),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='phone_type',
            field=models.IntegerField(choices=[(1, 'telefon domowy'), (2, 'telefon służbowy'), (3, 'telefon komórkowy')]),
        ),
    ]
