# Generated by Django 2.0.5 on 2018-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0002_auto_20180710_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='flat_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Numerr mieszkania'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='street_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='street_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='firstname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='surname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Numer telefonu'),
        ),
    ]
