# Generated by Django 2.0.5 on 2018-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0003_auto_20180714_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='street_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='street_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(1, 'email prywatny'), (2, 'email służbowy')], null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='firstname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='surname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='phone_type',
            field=models.IntegerField(choices=[(1, 'telefon domowy'), (2, 'telefon służbowy'), (3, 'telefon komórkowy')], null=True),
        ),
    ]
