# Generated by Django 2.0.5 on 2018-07-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0004_auto_20180714_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='adres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osoba', to='userstories.Adres'),
        ),
    ]
